name: Second Workflow

on: 
  workflow_run:
    workflows: ["First Workflow"]

    types:
      - completed

jobs:
job1:
if: ${{ github.event.workflow_run.conclusion == 'success' }}

job2:
    first-workflow:
      runs-on: ubuntu-latest
      steps:
        - name: Testing directory
          run: |
            ls -l
            mkdir testing-2
            ls -l

    