name: First Workflow

on: [push]

jobs:
  First-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Testing directory
        run: |
          ls -all
          mkdirl testing-1
          echo "creating directory"
          ls -ll

    