name: Second Workflow

on: 
  workflow_run:
    workflows: ["First Workflow"]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    types:
      - completed

jobs:
  First-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Testing directory
        run: |
        ls -al
        mkdir testing-2
        ls -l

    