name: Second-Workflow

on: 
  workflow_run:
    workflows: ["First-Workflow"]

    types:
      - completed

jobs:
    second-workflow:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      runs-on: ubuntu-latest
      steps:
        - name: Testing directory
          run: |
            ls -l
            mkdir testing-2
            ls -l

    