name: Second-Workflow

on: 
  workflow_run:
    workflows: ["First-Workflow"]

    types:
      - completed
  workflow_dispatch:

env:
  second-workflow: Second-Workflows

jobs:
    second-workflow:
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      environment: ${{ env.second-workflow }}
      runs-on: ubuntu-latest
      steps:
        - name: Testing directory
          run: |
            ls -l
            mkdir testing-2
            echo "second-workflow"
            ls -l

    