name: First-Workflow

on: [push]

jobs:
  First-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Testing directory
        run: |
          ls -al
          mkdir testing-1
          echo "creating directory in workflow-1"
          ls -l

    